export interface ClubBadge {
  initials: string;
  color: string;
}

// Monogram badges (initials + primary brand colour), not official crests —
// avoids reproducing trademarked club logos while still giving a visual cue.
export const clubBadges: Record<string, ClubBadge[]> = {
  "aalborg-stadion": [{ initials: "AS", color: "#001F3F" }],
  "achter-de-kazerne": [{ initials: "ADK", color: "#FFD700" }],
  "allianz-arena": [{ initials: "AA", color: "#DC052D" }],
  "allianz-parque": [{ initials: "AP", color: "#003DA5" }],
  "allianz-riviera": [{ initials: "AR", color: "#0055CC" }],
  "allianz-stadium-turin": [{ initials: "AST", color: "#000000" }],
  "amsterdam-arena": [{ initials: "AA", color: "#C8102E" }],
  "arena-abe-lenstra": [{ initials: "AAL", color: "#FFC52F" }],
  "arena-castelao": [{ initials: "AC", color: "#0055CC" }],
  "arena-corinthians": [{ initials: "AC", color: "#000000" }],
  "arena-das-dunas": [{ initials: "ADD", color: "#FFD700" }],
  "arena-de-pernambuco": [{ initials: "ADP", color: "#C8102E" }],
  "arena-lviv": [{ initials: "AL", color: "#FFD700" }],
  "artemio-franchi": [{ initials: "AF", color: "#8B0000" }],
  "ashton-gate": [{ initials: "AG", color: "#E30613" }],
  "asim-ferhatovic-stadium": [{ initials: "AFS", color: "#003DA5" }],
  "atanasio-girardot": [{ initials: "AG", color: "#C8102E" }],
  "ataturk-olimpiyat-stadyumu": [{ initials: "AOS", color: "#FFD700" }],
  "audi-sportpark": [{ initials: "AS", color: "#00A3E0" }],
  "aviva-stadium": [{ initials: "AS", color: "#FFFFFF" }],
  "balaidos": [{ initials: "B", color: "#0055CC" }],
  "bayarena": [{ initials: "B", color: "#E30613" }],
  "beira-rio": [{ initials: "BR", color: "#C8102E" }],
  "benteler-arena": [{ initials: "BA", color: "#C8102E" }],
  "borg-el-arab-stadium": [{ initials: "BEAS", color: "#001F3F" }],
  "brainpark-stadion": [{ initials: "BS", color: "#C8102E" }],
  "cairo-international-stadium": [{ initials: "CIS", color: "#FFFFFF" }],
  "camp-nou": [{ initials: "CN", color: "#A50044" }],
  "celtic-park": [{ initials: "CP", color: "#018749" }],
  "centenario": [{ initials: "C", color: "#FFD700" }],
  "constant-vanden-stock": [{ initials: "CVS", color: "#7C3C3B" }],
  "craven-cottage": [{ initials: "CC", color: "#000000" }],
  "daugava-stadium": [{ initials: "DS", color: "#C8102E" }],
  "de-kuip": [{ initials: "DK", color: "#E31937" }],
  "deutsche-bank-park": [{ initials: "DBP", color: "#C8102E" }],
  "doosan-arena": [{ initials: "DA", color: "#0055CC" }],
  "eden-arena": [{ initials: "EA", color: "#001F3F" }],
  "el-camin": [{ initials: "EC", color: "#FFD700" }],
  "el-sadar": [{ initials: "ES", color: "#C8102E" }],
  "elland-road": [{ initials: "ER", color: "#FFFFFF" }],
  "emirates-stadium": [{ initials: "ES", color: "#EF0107" }],
  "ernst-happel-stadion": [{ initials: "EHS", color: "#ED2939" }],
  "estadi-cornella": [{ initials: "EC", color: "#003DA5" }],
  "estadi-cornella-el-prat": [{ initials: "ECEP", color: "#003DA5" }],
  "estadi-nou": [{ initials: "EN", color: "#003DA5" }],
  "estadio-anoeta": [{ initials: "EA", color: "#003DA5" }],
  "estadio-azteca": [{ initials: "EA", color: "#003DA5" }],
  "estadio-cornella-el-prat": [{ initials: "ECEP", color: "#003DA5" }],
  "estadio-corona": [{ initials: "EC", color: "#C8102E" }],
  "estadio-da-luz": [{ initials: "EDL", color: "#E31B23" }],
  "estadio-da-madeira": [{ initials: "EDM", color: "#E30613" }],
  "estadio-do-bonfim": [{ initials: "EDB", color: "#C8102E" }],
  "estadio-do-dragao": [{ initials: "EDD", color: "#003DA5" }],
  "estadio-dragao": [{ initials: "ED", color: "#003DA5" }],
  "estadio-general-pablo-rojas": [{ initials: "EGPR", color: "#001F3F" }],
  "estadio-general-severiano": [{ initials: "EGS", color: "#C8102E" }],
  "estadio-jalisco": [{ initials: "EJ", color: "#C8102E" }],
  "estadio-jose-maria-morelos": [{ initials: "EJMM", color: "#FFD700" }],
  "estadio-la-condomina": [{ initials: "ELC", color: "#E30613" }],
  "estadio-luzhniki": [{ initials: "EL", color: "#C8102E" }],
  "estadio-mestalla": [{ initials: "EM", color: "#C8102E" }],
  "estadio-monumental": [{ initials: "EM", color: "#FFFFFF" }],
  "estadio-municipal-de-tigres": [{ initials: "EMDT", color: "#FFD700" }],
  "estadio-nacional": [{ initials: "EN", color: "#FFFFFF" }],
  "estadio-nacional-de-brasilia": [{ initials: "ENDB", color: "#00AA44" }],
  "estadio-nacional-metropolitano": [{ initials: "ENM", color: "#001F3F" }],
  "estadio-nemesio-diez": [{ initials: "END", color: "#003DA5" }],
  "estadio-nueva-condomina": [{ initials: "ENC", color: "#FFD700" }],
  "estadio-pitu-gomez": [{ initials: "EPG", color: "#C8102E" }],
  "estadio-presidente-peron": [{ initials: "EPP", color: "#FFFFFF" }],
  "estadio-ramon-sanchez-pizjuan": [{ initials: "ERSP", color: "#E30613" }],
  "etihad-stadium": [{ initials: "ES", color: "#6CABDD" }],
  "gazprom-arena": [{ initials: "GA", color: "#003DA5" }],
  "georgios-karaiskakis": [{ initials: "GK", color: "#E31B23" }],
  "goodison-park": [{ initials: "GP", color: "#003DA5" }],
  "groupama-stadium": [{ initials: "GS", color: "#0055CC" }],
  "helsinki-olympic-stadium": [{ initials: "HOS", color: "#003DA5" }],
  "houphouet-boigny-stadium": [{ initials: "HBS", color: "#00AA44" }],
  "ibrox-stadium": [{ initials: "RFC", color: "#0033A0" }],
  "itaquera": [{ initials: "I", color: "#FFFFFF" }],
  "jan-breydel": [{ initials: "JB", color: "#007A3D" }],
  "jan-breydelstadion": [{ initials: "JB", color: "#003DA5" }],
  "johan-cruyff-arena": [{ initials: "JCA", color: "#E42313" }],
  "juventus-stadium": [{ initials: "JS", color: "#000000" }],
  "king-power-stadium": [{ initials: "KPS", color: "#0055CC" }],
  "la-bombonera": [{ initials: "LB", color: "#003DA5" }],
  "la-cartuja": [{ initials: "LC", color: "#FFFFFF" }],
  "libertadores-de-america": [{ initials: "LDA", color: "#E41028" }],
  "london-stadium": [{ initials: "LS", color: "#7C3C3B" }],
  "lotto-park": [{ initials: "LP", color: "#7C3C3B" }],
  "maracana": [
    { initials: "CRF", color: "#E30613" },
    { initials: "FFC", color: "#8B0000" },
  ],
  "mestalla": [{ initials: "VCF", color: "#EE3524" }],
  "mhparena": [{ initials: "M", color: "#FFD700" }],
  "mineirao": [{ initials: "M", color: "#0066CC" }],
  "molineux": [{ initials: "M", color: "#FFC52F" }],
  "morumbi": [{ initials: "SPFC", color: "#FE0000" }],
  "old-trafford": [{ initials: "MUFC", color: "#DA291C" }],
  "orange-velodrome": [{ initials: "OV", color: "#0055CC" }],
  "parc-des-princes": [{ initials: "PSG", color: "#004170" }],
  "parken-stadium": [{ initials: "PS", color: "#E30613" }],
  "partizan-stadium": [{ initials: "PS", color: "#FFFFFF" }],
  "pge-narodowy": [{ initials: "PN", color: "#FFFFFF" }],
  "philips-stadion": [{ initials: "PS", color: "#E30613" }],
  "portman-road": [{ initials: "PR", color: "#003DA5" }],
  "principality-stadium": [{ initials: "PS", color: "#C8102E" }],
  "psv-stadion": [{ initials: "PS", color: "#C8102E" }],
  "red-bull-arena-leipzig": [{ initials: "RBAL", color: "#0066CC" }],
  "red-bull-arena-salzburg": [{ initials: "RBAS", color: "#0066CC" }],
  "regenbogenstadion": [{ initials: "R", color: "#FFD700" }],
  "rheinenergiestadion": [{ initials: "R", color: "#E30613" }],
  "san-mames": [{ initials: "ATH", color: "#EE2523" }],
  "san-siro": [
    { initials: "ACM", color: "#FB090B" },
    { initials: "INT", color: "#010E80" },
  ],
  "santiago-bernabeu": [{ initials: "RM", color: "#00529F" }],
  "signal-iduna-park": [{ initials: "BVB", color: "#FDE100" }],
  "soccer-city": [{ initials: "SC", color: "#FFC52F" }],
  "st-james-park": [{ initials: "NUFC", color: "#241F20" }],
  "st-mary-s-stadium": [{ initials: "SFC", color: "#FFFFFF" }],
  "stade-de-france": [{ initials: "FFF", color: "#1B1B7A" }],
  "stade-de-la-meinau": [{ initials: "RCSA", color: "#001F3F" }],
  "stade-du-roudourou": [{ initials: "EA", color: "#C8102E" }],
  "stade-geoffroy-guichard": [{ initials: "ASSE", color: "#1BA0D6" }],
  "stade-oceane": [{ initials: "FCN", color: "#FFC52F" }],
  "stade-velodrome": [{ initials: "OM", color: "#0055CC" }],
  "stadio-arechi": [{ initials: "UC", color: "#0055CC" }],
  "stadio-carlo-castellani": [{ initials: "EC", color: "#0055CC" }],
  "stadio-della-juventus": [{ initials: "JUV", color: "#000000" }],
  "stadio-ferraris": [{ initials: "UC", color: "#C8102E" }],
  "stadio-maradona": [{ initials: "SSC", color: "#0055CC" }],
  "stadio-olimpico": [
    { initials: "ASR", color: "#8E1F2F" },
    { initials: "SSL", color: "#87D8F7" },
  ],
  "stadio-renato-dall-ara": [{ initials: "BFC", color: "#C60B1E" }],
  "stadio-san-paolo": [{ initials: "SSC", color: "#0099D8" }],
  "stadion-antonis-papadopoulos": [{ initials: "AEK", color: "#003DA5" }],
  "stadion-gelredome": [{ initials: "VIT", color: "#FFC52F" }],
  "stadion-haarlem": [{ initials: "HFC", color: "#003DA5" }],
  "stadion-letzigrund": [{ initials: "FCZ", color: "#C8102E" }],
  "stadion-maksimir": [{ initials: "GNK", color: "#FFFFFF" }],
  "stadion-polissya": [{ initials: "VK", color: "#003DA5" }],
  "stadion-valeriy-lobanovskiy": [{ initials: "DYK", color: "#0066CC" }],
  "swansea-city-stadium": [{ initials: "SCFC", color: "#000000" }],
  "swissporarena": [{ initials: "YB", color: "#FFD700" }],
  "telia-parken": [{ initials: "FC", color: "#C8102E" }],
  "the-hawthorns": [{ initials: "WBA", color: "#FFFFFF" }],
  "tottenham-hotspur-stadium": [{ initials: "THFC", color: "#132257" }],
  "ullevaal-stadion": [{ initials: "IFK", color: "#0055CC" }],
  "veltins-arena": [{ initials: "FC", color: "#003DA5" }],
  "villa-park": [{ initials: "AVFC", color: "#7A2149" }],
  "wanda-metropolitano": [{ initials: "ATM", color: "#CB3524" }],
  "wildparkstadion": [{ initials: "KSC", color: "#003DA5" }],
};
