CREATE TABLE "stadium_translations" (
	"stadium_slug" text NOT NULL,
	"locale" text NOT NULL,
	"name" text NOT NULL,
	"club" text NOT NULL,
	"city" text NOT NULL,
	"country" text NOT NULL,
	"league" text NOT NULL,
	"description" text NOT NULL,
	"nearest_airport" text NOT NULL,
	"public_transport" text NOT NULL,
	"from_airport" text NOT NULL,
	"best_time_to_visit" text NOT NULL,
	"what_to_see" jsonb NOT NULL,
	"shop_description" text NOT NULL,
	"shop_products" jsonb NOT NULL,
	"gallery_alts" jsonb NOT NULL,
	"hero_alt" text NOT NULL,
	"insider_tip" text NOT NULL,
	"record_match_label" text DEFAULT '' NOT NULL,
	"owner" text DEFAULT '' NOT NULL,
	"anecdote" text DEFAULT '' NOT NULL,
	"metro_line_names" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"metro_line_colors" jsonb DEFAULT '[]'::jsonb NOT NULL,
	CONSTRAINT "stadium_translations_stadium_slug_locale_pk" PRIMARY KEY("stadium_slug","locale")
);
--> statement-breakpoint
CREATE TABLE "stadiums" (
	"slug" text PRIMARY KEY NOT NULL,
	"country_code" text NOT NULL,
	"lat" double precision NOT NULL,
	"lng" double precision NOT NULL,
	"capacity" integer NOT NULL,
	"year_opened" integer NOT NULL,
	"currency" text NOT NULL,
	"guided_tour_price_from" integer NOT NULL,
	"guided_tour_url" text NOT NULL,
	"match_ticket_price_from" integer NOT NULL,
	"match_ticket_url" text NOT NULL,
	"official_website" text NOT NULL,
	"shop_url" text NOT NULL,
	"hero_image_src" text NOT NULL,
	"gallery" jsonb NOT NULL,
	"airport_distance_km" integer NOT NULL,
	"nearby_hotels" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"nearby_airbnbs" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"nearby_restaurants" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"transit_lines" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"initial_architect" text DEFAULT '' NOT NULL,
	"renovations" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"record_attendance" integer,
	"club_logo_url" text DEFAULT '' NOT NULL,
	"club_color_primary" text DEFAULT '' NOT NULL,
	"club_color_secondary" text DEFAULT '' NOT NULL,
	"airport_name" text DEFAULT '' NOT NULL,
	"airport_logo_url" text DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "stadium_translations" ADD CONSTRAINT "stadium_translations_stadium_slug_stadiums_slug_fk" FOREIGN KEY ("stadium_slug") REFERENCES "public"."stadiums"("slug") ON DELETE cascade ON UPDATE no action;